#!/usr/bin/env bash
#
# document-dependencies.sh -- record the current Python environment to
# `dependencies.txt`, for provenance of a database ingest / release.
#
# The file records: the generation timestamp (UTC), the git HEAD commit
# hash, the venv's Python version, and the full `venv/bin/pip freeze`
# output. Commit `dependencies.txt` and tag the release so the snapshot
# is recoverable per release via the git tag.
#
# Aborts if the working tree has uncommitted changes to tracked files,
# so the recorded Git HEAD faithfully represents the code. Untracked
# files are not fatal but produce a warning on stderr.
#
# IMPORTANT: this records `pip freeze` of the live venv AS-IS. `pip` never
# uninstalls a package just because it was dropped from pyproject.toml, so
# an existing venv can carry orphaned (no-longer-declared) packages that
# would be silently baked into dependencies.txt. Run this only against a
# freshly rebuilt venv (`rm -rf venv && ./run-setup-venv.sh --dev`) so the
# snapshot reflects exactly the declared dependency closure. See the
# "Versioning workflow" section of README.md.
#
set -euo pipefail

# Run from the repository root (where venv/ and dependencies.txt live),
# regardless of the directory this script is invoked from.
cd "$(dirname "${BASH_SOURCE[0]}")"

output_file=dependencies.txt

# Refuse to run with a dirty working tree: a recorded Git HEAD would
# otherwise not faithfully represent the code. "Dirty" here means
# uncommitted changes to tracked files; the generated output file
# itself is excluded, and untracked files do not count.
if ! git diff --quiet HEAD -- ":!${output_file}"; then
    echo "ERROR: working tree has uncommitted changes to tracked files:" >&2
    git diff --name-only HEAD -- ":!${output_file}" >&2
    echo "Commit or stash them before recording dependencies." >&2
    exit 1
fi

# Untracked files are not an error, but they are also not captured by
# the recorded Git HEAD -- warn (to stderr) so the user is aware.
untracked="$(git ls-files --others --exclude-standard --directory -- ":!${output_file}")"
if [ -n "${untracked}" ]; then
    echo "WARNING: untracked files present (not captured by the recorded Git HEAD):" >&2
    echo "${untracked}" >&2
fi

timestamp="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
git_head="$(git rev-parse HEAD)"
python_version="$(venv/bin/python --version)"

{
    echo "# Environment snapshot -- generated by document-dependencies.sh"
    echo "# Generated (UTC): ${timestamp}"
    echo "# Git HEAD:        ${git_head}"
    echo "# Python:          ${python_version}"
    echo "#"
    echo "# Below: output of \`venv/bin/pip freeze\`"
    venv/bin/pip freeze
} > "${output_file}"

echo "Wrote ${output_file} (git HEAD ${git_head}, ${python_version})."
