#!/usr/bin/env bash
#
# document-dependencies.sh -- record the Python environment to
# `dependencies.txt`, for provenance of a database ingest / release.
#
# Modes (choose one; default is --fresh):
#
#   --fresh      (DEFAULT) Build a throwaway venv in a temp dir, install
#                ".[dev]" into it, and freeze THAT. Correct by construction:
#                the snapshot is exactly the declared dependency closure of
#                pyproject.toml, with no orphans possible, and ./venv is left
#                untouched. This is the primary, release-oriented use case.
#                NOTE: a fresh install resolves to the latest compatible
#                versions available at run time, so re-running is not
#                necessarily idempotent.
#
#   --from-venv  Freeze the existing ./venv AS-IS. Faithful to the
#                environment that actually ran (e.g. the venv that produced
#                a database ingest), but only as clean as ./venv itself:
#                `pip` never uninstalls a package just because it was dropped
#                from pyproject.toml, so an orphaned (no-longer-declared)
#                package can linger in ./venv and be baked into the snapshot.
#                Use only when you are confident ./venv matches the declared
#                closure (i.e. you do not need to rebuild it first).
#
# The file records: the generation timestamp (UTC), the git HEAD commit
# hash, the Python version, which mode produced it, and the full `pip freeze`
# output. Commit `dependencies.txt` and tag the release so the snapshot is
# recoverable per release via the git tag. See the "Versioning workflow"
# section of README.md.
#
# Aborts if the working tree has uncommitted changes to tracked files,
# so the recorded Git HEAD faithfully represents the code. Untracked
# files are not fatal but produce a warning on stderr.
#
set -euo pipefail

# Run from the repository root (where venv/ and dependencies.txt live),
# regardless of the directory this script is invoked from.
cd "$(dirname "${BASH_SOURCE[0]}")"

# --- parse arguments -------------------------------------------------------
mode=fresh
for arg in "$@"; do
    case "${arg}" in
        --fresh)     mode=fresh ;;
        --from-venv) mode=from-venv ;;
        *) echo "Unknown argument: ${arg}" >&2
           echo "Usage: $0 [--fresh | --from-venv]" >&2
           exit 1 ;;
    esac
done

output_file=dependencies.txt

# Refuse to run with a dirty working tree: a recorded Git HEAD would
# otherwise not faithfully represent the code. "Dirty" here means
# uncommitted changes to tracked files; the generated output file
# itself is excluded, and untracked files do not count.
if ! git diff --quiet HEAD -- ":!${output_file}"; then
    echo "ERROR: working tree has uncommitted changes to tracked files:" >&2
    git diff --name-only HEAD -- ":!${output_file}" >&2
    echo "Commit or stash them before recording dependencies." >&2
    exit 1
fi

# Untracked files are not an error, but they are also not captured by
# the recorded Git HEAD -- warn (to stderr) so the user is aware.
untracked="$(git ls-files --others --exclude-standard --directory -- ":!${output_file}")"
if [ -n "${untracked}" ]; then
    echo "WARNING: untracked files present (not captured by the recorded Git HEAD):" >&2
    echo "${untracked}" >&2
fi

# --- select the venv to freeze ---------------------------------------------
if [ "${mode}" = fresh ]; then
    # Build a throwaway venv from the declared dependency closure. Installing
    # editable (-e) from the repo root makes pip freeze emit the same git VCS
    # line for the project itself as the --from-venv mode does, so the two
    # modes produce comparable output.
    tmp_root="$(mktemp -d)"
    trap 'rm -rf "${tmp_root}"' EXIT
    venv_bin="${tmp_root}/venv/bin"
    echo "Building a throwaway venv in ${tmp_root}/venv from pyproject.toml ..." >&2
    python3.12 -m venv "${tmp_root}/venv"
    "${venv_bin}/pip" install -q -e ".[dev]"
    freeze_source='a fresh throwaway venv installed from ".[dev]" (--fresh)'
else
    if [ ! -x venv/bin/pip ]; then
        echo "ERROR: ./venv not found (no venv/bin/pip)." >&2
        echo "       Create it with ./run-setup-venv.sh --dev, or use --fresh" >&2
        echo "       to build a throwaway venv from pyproject.toml." >&2
        exit 1
    fi
    venv_bin="venv/bin"
    freeze_source='the existing ./venv as-is (--from-venv)'
fi

timestamp="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
git_head="$(git rev-parse HEAD)"
python_version="$("${venv_bin}/python" --version)"

{
    echo "# Environment snapshot -- generated by document-dependencies.sh"
    echo "# Generated (UTC): ${timestamp}"
    echo "# Git HEAD:        ${git_head}"
    echo "# Python:          ${python_version}"
    echo "# Source:          ${freeze_source}"
    echo "#"
    echo "# Below: output of \`pip freeze\`"
    "${venv_bin}/pip" freeze
} > "${output_file}"

echo "Wrote ${output_file} (git HEAD ${git_head}, ${python_version}, mode: ${mode})."
